### ISSUE TITLE
Do not suggest archival of repositories

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/information#279]
label: editorial

The [current repo-overview.md](https://github.com/solid/information/blob/a84a0790d2c1deb6ecdf5d06171d30826c951aee/repo-overview.md#repositories-without-known-link-to-activity-that-can-be-archived) suggests the archival of a long list of repositories.

This proposal is misguided, in the sense that many of the listed repositories are important software libraries (pertains to #278).

There is also a suggestion to archive old repositories. However, date of last update is also not a good reason for archival.  To take one example, the [wac-allow](https://github.com/solid/wac-allow) library has received little updates, not because it was abandoned, but because it is feature-complete and currently assumed to be bug-free. Archiving it would mean that people cannot file bugs or ask questions anymore, which would be unwise for an actively used library.

Assigning to Community Manager.

**Comment by Vinnl** [comment]
> However, date of last update is also not a good reason for archival. 

As far as I can see it, that's not the reason to archive it. The reason for archival is that nobody actively cares about it enough to mark it as not-to-archive:

> If you know about the the following repositories being linked to current activity submit a pull request to take the repository off this list and add the repository to the table of activity above.

The Community Manager has been bugging people to update that list to mark active repositories that they know of, since there isn't really a good way to tell otherwise.

So two asks:

1. Could you submit a PR to mark the ones you know are active as such?
2. What other channels could be used to ask people to indicate their repositories as active, as apparently the ones used so far are not sufficient?

Also a note to keep in mind that archival can always be undone, so the action of archival would be an additional channel of notification - when it turns out it needs to be used after all, it can be unarchived again.

**Comment by RubenVerborgh** [comment]
> * Could you submit a PR to mark the ones you know are active as such?

None as far as I know. We did a major cleanup round just a couple of months ago. Everything that was outdated, has been archived already.

> * What other channels could be used to ask people to indicate their repositories as active, as apparently the ones used so far are not sufficient?

Insufficiently people see it here. An issue should be made to every repo we plan to archive (which, as per my indication above, would be a low number).

**Comment by Mitzi-Laszlo** [comment]
Maybe time to put down the red pen and pick up the green pen? Active proposals describing what the aim of each repo is and who is working on getting to that aim would be helpful. @RubenVerborgh You seem to be in a good place to put that information forward. If you have suggestions on other people to reach out to let me know.

**Comment by RubenVerborgh** [comment]
> Maybe time to put down the red pen

Red pen is important; that's how we make progress on GitHub. We flag issues and then assign someone to do them.

> and pick up the green pen?

Done in #280.

**Comment by Mitzi-Laszlo** [comment]
Thanks Ruben https://github.com/solid/information/pull/280/files is really helpful :)
