### ISSUE TITLE
Provide resources related to vocabularies

### ISSUE THREAD

**Issue by NSeydoux** [solid/information#282]
The documentation should provide resources in order to:
- be aware of the vocabularies that are essential to solid app development
- have a general idea of very common linked data vocabularies
- enable finding existing vocabularies 
- support the creation of one's own vocabulary

**Comment by megoth** [comment]
Just want to mention https://github.com/solid/solid-namespace, that should answer at least partially answer your first point.

Otherwise I agree that we need resource that allows for finding existing and easily create new vocabularies (and shapes, I would add). There are [some good discussions on it in the forum](https://forum.solidproject.org/), but we need better tooling in general.

**Comment by Mitzi-Laszlo** [comment]
@NSeydoux this is great! 

I've been trying to get all the documentation into this file https://github.com/solid/information/tree/master/documentation so that it's easier to navigate. If there is information in other repos let's try and concentrate it into this file or at least link to it.

**Comment by NSeydoux** [comment]
Yes, I added a new file in this folder, but I realised after I began writing that I should fork the repo and PR my way back when I am done :). And thanks @megoth for the pointer !

**Comment by Mitzi-Laszlo** [comment]
Thanks Nicolas for working on this for the solidproject.org repo
