### ISSUE TITLE
Define purpose of each Gitter channel

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/information#75]
The gitter channels could be focused for specific interest groups with defined goals. 

For example: 

Channel: [solid-spec](https://gitter.im/solid/solid-spec)
Description: A place for the [w3c Solid community group](https://www.w3.org/community/solid/) to talk about the Solid specifications
Action: Make invite only to W3C Solid Community Group

Channel: Pod Providers
Description: A place for Pod Providers to talk about developing a Pods. 
Action: Open and make invite only to Pod Providers

Channel: [app-development](https://gitter.im/solid/app-development)
Description: A place for Solid App developers to talk about building Solid apps. 
Action: Make invite only to Solid App developers

Channel: Solid Developer Tools
Description: A place for Solid Developer Tool builders to talk about building Solid developer tools. 
Action: 

Channel: Solid Events
Description: A place for Solid Event organisers to talk about Solid Event organisation 
Action: Open channel and invite event organisers

Channel: Solid Chat Project
Action: Close project and merge with Solid Apps. 

Channel:  [suggestions](https://gitter.im/solid/suggestions)
Action: Close

Channel: [introductions](https://gitter.im/solid/introductions)
Action: Close (same as Solid Chat)

Channel: [node-solid-server](https://gitter.im/solid/node-solid-server)
Action: Close once project over [NSS-5.0.0](https://github.com/orgs/solid/projects/1) 

Channel: [site-and-docs](https://gitter.im/solid/site-and-docs)
Action: ?

Any other project needs it’s own chat https://github.com/orgs/solid/projects

**Comment by michielbdejong** [comment]
I think we should keep the node-solid-server channel open, because it serves a specific purpose of helping people very specifically with installing and using the server. But maybe we want to rename it to server-development, to align with the app-development one?

**Comment by csarven** [comment]
>Channel: solid-spec
>Action: Make invite only to W3C Solid Community Group

Are you assuming that solid-spec is the "official" chat channel of W3C Solid CG?

W3C CGs are normally open to public participation (sit-in). Why would solid-spec be more restrictive? Which actors are going to "govern" the channel's management for the CG?

>Channel: app-development
>Action: Make invite only to Solid App developers

That creates an exclusive community. How does anyone benefit from that? How does the Solid ecosystem benefit from that? Who is going to "govern" membership?

>Channel: Solid Chat Project
>Action: Close project and merge with Solid Apps.

solid/chat and app-development have completely different purpose. Why should they be merged?



Keep `node-solid-server` as is because it has a very *specific* purpose - it is associated with the git repo and its development.

Create a new channel like `server-development` in order to widen the discussion on various "Solid servers", not only node-solid-server. That ties in with solid-spec development which is intended to cover different servers and clients using the same underlying specifications and practices.

**Comment by csarven** [comment]
Alternative to creating server-development, use app-development to include server development discussion - they're all applications in the general sense. I think it would be healthy to mix server and client application developers together so that they can learn form and help each other. If they are kept separate, there are less discussions, and slower global progress.

**Comment by michielbdejong** [comment]
Hey @csarven, good points! I guess there are multiple ways we can organize the channels, maybe we should first decide what our goal is. I actually thought less discussions was a good thing, as it saves everybody time and leaves the channels open for specific and on-topic questions people have, but your idea of fostering more broad and cross-disciplinary chat is also an interesting idea.

**Comment by melvincarvalho** [comment]
It would be nice is solid/chat were to be kept open.  There is a lot of project history there, useful tips, code snippets and so on ...

**Comment by csarven** [comment]
This issue is masqueraded as defining but in fact **re**defines. There is no goal here because there is no problem stated.

The onus is on those to present their case on the changes ie. the **re**definitions and changes in expected community behaviour before messing with what's already in place. Not to forget, mentioning or taking necessary measures to avoid or limit any damage or affects on the community and beyond. The primary chat channels eg. solid/chat , solid/node-solid-server , have been working well-enough for the "Solid community" for several years even **prior** to people joining the Solid project (still under a year!?). Perhaps a reasonable starting point *before* doing anything is to understand and blend in with the actual community instead of making *top-down decisions*.

Was there some survey presented to the Solid community to understand its needs *prior* to creating this issue as a **re**definition and randomly shuffling things around? If so, where is the data? What are the actual/tangible shortcomings of the existing channel organisation? Where is the supporting data or let alone an argument as to why the change would be preferable for the community? I see none of this.

I say this not to dismiss potential progress but that "Solid community" decisions are actually grounded on some reality. If this issue is going to be carried out regardless of the "Solid community"'s behaviour and preferences, then why bother with the issue in the first place? Just do it, but don't advertise it as a "Solid community" decision in the end. Call it "what I think because I have access to do it". I've lost count of this sort of recurring behaviour ie. decisions and changes are being put in place or pushed under the disguise of "Solid community" when it really isn't.

So, if anyone wants to add new channels because some ideas or work can be better carried out and that there is an actual community need, voiced by the "Solid community", that's all great, take the necessary steps. I would rather not see a community get wiped off ("just relocated") because...? without taking on the most *basic* precautions.

I've already responded to the individual "proposals" earlier, so I won't repeat.

**Comment by Mitzi-Laszlo** [comment]
Would seem that there is a general preference to keep all chat channels open. 

The problem I was looking to solve with this suggestion was that I have heard comments that there are many people wishing to talk about different things and because there is no threading in gitter the conversations become difficult to follow. 

It's just a suggestion, so ok to just ignore and close.
